name: Build and Push

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - uses: mr-smithers-excellent/docker-build-push@v1.0
       with:
        image: jptaku2/openjdk
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
