on:
  push:
    branches:
      - master
jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1
      - uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: jptaku2/openjdk
          registry: docker.io
          tag: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
