on:
  push:
    branches:
      - master
jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1
      - name: Build, tag, and push image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        run: |
          IMAGE_TAG=$(git rev-parse HEAD^2)
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker tag $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest